name: Maze Generation API
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  repository_dispatch:
    types: [generate]
jobs:
  permissions: write-all
  run_if_failure:
    if: ${{ !github.event.client_payload.passed }}
    runs-on: ubuntu-latest
    steps:
      - env:
          MESSAGE: ${{ github.event.client_payload.message }}
        run: echo $MESSAGE